### ISSUE TITLE
Make a figure to illustrate the genotyping algo?

### ISSUE THREAD

**Issue by jmonlong** [jmonlong/manu-vgsv#70]
I move the fig1a (the cartoon that shows what a structural variant looks in the graph) to the supplement with the text introducing genome graphs. A better fig1a would be a cartoon that shows the genotyping algo described at the begining of the results section. Maybe something that shows:

- a graph with a SV (and some SNVs)
- reads mapped to it
- a snarls highlighted
- two paths that represent the genotype prediction.

We could either start from the cartoon I made (former fig1a) or one of Erik's figure like Glenn suggested. Or maybe we already have this kind of illustration somewhere? @glennhickey @adamnovak did you ever used something like that to explain the genotyping approach?

**Comment by glennhickey** [comment]
I've done a bunch of these way back when.  Ex Figure three from https://www.biorxiv.org/content/10.1101/101378v1.full, but they all emphasize sample graphs and augmentation which aren't so relevant here.

I think a cartoon is the way to go, where reads support two paths through the graph and the reference path is indicated and a VCF line comes out the other end.   Adding some reads to your cartoon would probably work, otherwise maybe marking up a small tubemap?

**Comment by jmonlong** [comment]
Here is what I wanted to make for Wednesday's presentation but didn't have time. For the paper maybe something like the bottom part is enough. [The google drawing](https://docs.google.com/drawings/d/1yiUkcnC5XCwfVBn-EB-09mjzamBZV8YR-VKVU15RJX0/edit?usp=sharing) if someone feel like tweaking it.

![mapping-geno-insertion-linear-vs-graph](https://user-images.githubusercontent.com/5704457/57506366-78529780-72b0-11e9-88ba-6e981e791bff.jpg)

**Comment by ekg** [comment]
Are we discussing snarls in the text? I wonder if the term might be a
little unclear. We could just call them bubbles.

**Comment by eldariont** [comment]
Yes, snarls are discussed in the Methods section. I have made an attempt of taking Jean's drawing and focusing on the bottom part so that we can use it as Figure 1a. What do you think?

![Genotyping figure](https://user-images.githubusercontent.com/6477692/57527939-37e72e00-7331-11e9-9232-dd0519706e71.png)

**Comment by eldariont** [comment]
In case you want to edit: https://docs.google.com/drawings/d/1Ol8dIkmmx7ug17drHnb0AfbHJERYxD55_SWTDo6Z2To/edit?usp=sharing

**Comment by jmonlong** [comment]
Looks good, more compact, I like it. 

Yes the idea was to illustrate the "call algorithm" in the methods section that talks about coverage, snarls, paths. We could also use bubble in the fig 1a and in the method section refer to them when introducing snarls.

**Comment by glennhickey** [comment]
Yeah, thanks.  This is looking good.  I don't think we want to show a SNP
though as it's not super relevant to the text.  I will try to change it to
an inversion or deletion.

**Comment by jmonlong** [comment]
I think Glenn's version is good for fig1a so I just merged the corresponding PR #81.
