### ISSUE TITLE
Compare mapping to sample graph vs. mapping to full graph

### ISSUE THREAD

**Issue by eldariont** [jmonlong/manu-vgsv#76]
This is a good comment that Jonas made in the Google doc:
_It might be interesting to compare mapping/identity statistics to the sample graph with the full graph. This would give an indication on the quality of the genotyping since wrong genotypes would likely result in fewer mapped reads and lower identity._
I have the data now and will generate a plot tomorrow.

**Comment by glennhickey** [comment]
Good points.  The mapping experiments don't allow us to just cut off
variation below 50bp like we do in the rest of the paper, so we have to be
careful.

For "whole-graph" comparisons, I guess we would need to include SNP calls
in the VCF graph in order to properly compare it to the Cactus graph.  This
isn't hard from a vg point of view, I don't think, but I don't know if you
have a way of getting SNPs from your data.  Moving to the supplement and
making clear that this effect could be the source of the signal we're
seeing seems reasonable too.  Like you say, it's a benefit of Cactus that
you get all variation from it as opposed to just SVs from asmvar.

Allowing the VCF sample graph to get augmented by vg call mitigates this
somewhat, but I think there could still be a bias here.  Toggling --recall
on and off changes the output substantially.  It may be fairer to run them
both without --recall.

Graph normalization can have a substantial effect on mapqs for the reasons
you state in point 2).  Are you normalizing your graphs?  Putting it
through "vg mod -U 10 graph.vg | vg mod -X 32 -" could help considerably.
It did for the HGSVC graphs which suffered from the same problem (similar
insertions from different samples lowering MAPQ).

**Comment by eldariont** [comment]
Thanks Glenn,
I included `--recall` only for the cactus graph because it was the best parameter setting for both graphs. In that way, it is a fair comparison because it reflects the structural difference between the graphs. Running both without `--recall` would make the results on the cactus graph slightly worse and I'm also a bit hesitant to re-run everything now at this late stage.

I'm normalizing both graphs with `vg mod -X 32` but not with `vg -U 10`. Is the missing part the important bit? Changing it would require re-running everything, though, and would probably take some time..

**Comment by glennhickey** [comment]
It's the mod -U 10 that does the normalizing (it also unchops the nodes so
always needs to be followed by mod -X 32 in practice).  Not using it could
lower the MAPQ, though there is no way to know without trying.  I think
pushing MAPQ comparison on the whole graphs into the supplement and
mentioning normalization could be a factor is fine for now.  Though it
would be interesting to rerun at some point.

I guess using --recall with cactus and not using for construct is okay, if
individually these are the best parameter sets for each graph,
respectively.   I would expect these results to be fairly robust to minor
parameter differences, but --recall does lower the support threshold at
which a variant can be called.
